version: 2.1

aliases:
    - &cache-key dependency-cache-{{ checksum "package.json" }}
    - &cache-key-fallback dependency-cache-

executors:
    default:
        working_directory: ~/repo
        docker:
            - image: cimg/node:lts

jobs:
    checkout_code:
        executor: default
        steps:
            - checkout
            - persist_to_workspace:
                  root: ~/repo
                  paths:
                      - .
    test:
        executor: default
        steps:
            - attach_workspace:
                  at: ~/repo
            - restore_cache:
                  keys:
                      - *cache-key
                      - *cache-key-fallback
            - run: npm install
            - run: npm rebuild
            - save_cache:
                  key: *cache-key
                  paths:
                      - ./node_modules
            - run: npm run lint
            - run: npm test
            - persist_to_workspace:
                  root: ~/repo
                  paths:
                      - node_modules

    release:
        executor: default
        steps:
            - attach_workspace:
                  at: ~/repo
            - checkout
            - run: npm run semantic-release

workflows:
    version: 2
    build:
        jobs:
            - checkout_code
            - test:
                  requires:
                      - checkout_code
            - release:
                  context: org-global
                  requires:
                      - test
